---
title: "exploratorio resultados"
author: "Andrea Gomez"
date: "2024-08-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)
library(gt)
library(openxlsx)
options(scipen = 999)
```

```{r}
# canastas_indec <- read.xlsx("data/BASE_canastas.xlsx", 
#     sheet = "INDEC_17_23") %>% 
#   mutate(
#          var_rel_cbt = round(var_rel_cbt,1),
#          var_rel_cba = round(var_rel_cba,1)
#   )
# 
# canastas_ibp <- read.xlsx("data/BASE_canastas.xlsx", 
#     sheet = "IBP_17-23") %>% 
#   select(-4:-5) %>% 
#   mutate(CBT = round(as.numeric(CBT),2),
#          CBA = round(as.numeric(CBA),2),
#          var_rel_cbt = round(var_rel_cbt,1),
#          var_rel_cba = round(var_rel_cba,1)
#          )


canastas <- read.xlsx("data/BASE_canastas.xlsx", sheet = "TOTAL CANASTAS") %>% 
  mutate(mes = fct_relevel(mes, c("Enero", "Febrero","Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")))

# canastas <- rbind(canastas_indec,canastas_ibp) %>% 
#   mutate(mes = fct_relevel(mes, c("Enero", "Febrero","Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")))

class(canastas_ibp$CBT)

```
 
 
 
```{r}

esquisse::esquisser(canastas)
```
 
```{r}
ggplot(canastas) +
  aes(x = mes, y = var_rel_cba, fill = organismo) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = c("#42047e", "#07f49e")) +
  #scale_fill_viridis_d(option = "viridis", direction = 1) +
  ggthemes::theme_economist_white() +
  facet_wrap(vars(ano), scales = "free_y", ncol = 1)

```
```{r}


gra1 <- canastas %>% 
  #mutate(fecha = paste0(ano,mes)) %>% 
  filter(ano == 2023) %>% 
  ggplot() +
  aes(x = mes_n, y = var_rel_cba, group = organismo, colour = organismo) +
  geom_line(linewidth = 1) +
  geom_point()+
  scale_x_continuous(limits = c(1, 12), breaks = seq(1, 12, by = 1)) + 
    scale_color_manual(values = c("#42047e", "#07f49e")) +
  theme_bw() +
  labs(
    x = "mes",
    y = "porcentaje"
  ) +
  theme(legend.position = "bottom")

ggsave("gra1.png", width = 6, height = 4)
# png("gra1.png")
# print(gra1)
# dev.off()
  #facet_wrap(vars(ano), scales = "free_y", ncol = 2) +
   #ggthemes::theme_economist_white() #+ theme(axis.text.x = element_text(angle = 30))
  

```
 

```{r}
gra2 <- canastas %>% 
  #mutate(fecha = paste0(ano,mes)) %>% 
  filter(ano == 2023) %>% 
  ggplot() +
  aes(x = mes_n, y = var_rel_cbt, group = organismo, colour = organismo) +
  geom_line(linewidth = 1) +
  geom_point()+
  scale_x_continuous(limits = c(1, 12), breaks = seq(1, 12, by = 1)) + 
    scale_color_manual(values = c("#ff0f7b", "#f89b29")) +
  theme_bw() +
  labs(
    x = "mes",
    y = "porcentaje"
  ) +
  theme(legend.position = "bottom")

ggsave("gra2.png", width = 6, height = 4)
```


```{r}


ggplot(canastas) +
  aes(x = mes, y = CBA, fill = organismo) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = c("#42047e", "#07f49e")) +
  theme_minimal() +
  facet_wrap(vars(ano), scales = "free_y", ncol = 1)
```
 
```{r}


ggplot(canastas) +
  aes(x = mes, y = CBT, fill = organismo) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = c("#42047e", "#07f49e")) +
  theme_minimal() +
  facet_wrap(vars(ano), scales = "free_y", ncol = 1)
```
 
 
```{r}
tabla <- canastas %>% 
  pivot_wider(names_from = organismo, 
              values_from = c(CBA,CBT)) %>% 
  mutate(dif = CBA_INDEC - CBA_ISEPCI)
```


```{r}
tabla %>% 
  gt(groupname_col = "ano") %>% 
    tab_header(
    title = md("**Publicación de valores de canastas hogar tipo 2 por organismo**"),
    subtitle = md("enero 2019 a diciembre 2023")) %>% 
   tab_spanner(
    label = "CBA",
    columns = c(CBA_INDEC, CBA_ISEPCI)) %>% 
  tab_spanner(
    label = "CBT",
    columns = c(CBT_INDEC, CBT_ISEPCI)) %>% 
  cols_label(mes = '', CBA_INDEC = 'INDEC', CBA_ISEPCI = "ISEPCI", CBT_INDEC = 'INDEC', CBT_ISEPCI = "ISEPCI" ) %>% 
  cols_align(align = c("left"), columns = mes) %>% 
  tab_options(
      column_labels.background.color = "#f2eef4",
      heading.background.color = "#865596",
      row_group.background.color = "white",
      row_group.font.size = px(20),
      row_group.font.weight = "bolder",
      table.border.top.color = "white")

```
 
 
 
```{r}
esquisse::esquisser(canastas)
```
 
 