---
title: "tablas anexo"
output:
  word_document: default
  html_document: default
header-includes:
     \usepackage[labelformat=empty]{caption}
     \usepackage{longtable}
     \renewcommand{\contentsname}{Contenido}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(gt)
library(tidyverse)
library(openxlsx)
library(glue)

canastas <- read.xlsx("data/BASE_canastas_final.xlsx", sheet = "TOTAL CANASTAS") %>% 
  mutate(mes = fct_relevel(mes, c("Enero", "Febrero","Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre")))

```


```{r include=FALSE}

# Inicializamos un contador global
contador_tabla <- 0  

crear_tabla_canasta <- function(ano_seleccionado) {

  
   # Incrementamos el contador
  contador_tabla <<- contador_tabla + 1  
  
  tabla <- canastas %>% 
    mutate(var_rel_cbt = round(var_rel_cbt, 1),
           var_rel_cba = round(var_rel_cba, 1)) %>% 
    pivot_wider(names_from = organismo, 
                values_from = c(5:8)) %>%
    filter(ano == ano_seleccionado) %>% 
    select(mes, CBA_INDEC, var_rel_cba_INDEC, CBT_INDEC, var_rel_cbt_INDEC,
                CBA_ISEPCI, var_rel_cba_ISEPCI, CBT_ISEPCI, var_rel_cbt_ISEPCI)
  
  
    titulo <- glue("**Cuadro {contador_tabla}:** Valorización nominal mensual y variación relativa porcentual respecto al mes anterior de la   Canasta Básica Alimentaria (CBA) y de la Canasta Básica Total (CBT) para hogar tipo 2 en el Gran Buenos Aires. Año {ano_seleccionado}.")


  tabla %>%
    gt() %>% 
    tab_header(title = md(titulo)) %>% 
    tab_spanner(label = md("**INDEC**"),
                columns = c(CBA_INDEC, var_rel_cba_INDEC, CBT_INDEC, var_rel_cbt_INDEC)) %>% 
    tab_spanner(label = md("**ISEPCI**"),
                columns = c(CBA_ISEPCI, var_rel_cba_ISEPCI, CBT_ISEPCI, var_rel_cbt_ISEPCI)) %>% 
    cols_label(CBA_INDEC = 'CBA', CBA_ISEPCI = "CBA", 
               CBT_INDEC = 'CBT', CBT_ISEPCI = "CBT",
               var_rel_cba_ISEPCI = "variación relativa al mes anterior", 
               var_rel_cbt_ISEPCI = "variación relativa al mes anterior",
               var_rel_cba_INDEC = "variación relativa al mes anterior", 
               var_rel_cbt_INDEC = "variación relativa al mes anterior") %>% 
    cols_align(align = c("left"), columns = mes) %>% 
    cols_align(align = c("center"), columns = c(2:8)) %>% 
    tab_options(
      table_body.hlines.style = "none",
      column_labels.border.top.color = "black",
      column_labels.border.bottom.color = "black",
      table_body.border.bottom.color = "black",
      table.font.size = "13px") %>% 
    fmt_number(columns = c(2,4,6,8),
               decimals = 2,
               sep_mark = ".",
               dec_mark = ",") %>%
    fmt_number(columns = c(3,5,7,9),
               decimals = 1,
               sep_mark = ".",
               dec_mark = ",") %>%
    # data_color(columns = var_rel_cba_ISEPCI,
    #            rows = var_rel_cba_ISEPCI > 10,
    #            direction = "column",
    #            palette = "viridis") %>% 
    # data_color(columns = var_rel_cbt_ISEPCI,
    #            rows = var_rel_cbt_ISEPCI > 10,
    #            direction = "column",
    #            palette = "viridis") %>% 
    # data_color(columns = var_rel_cba_INDEC,
    #            rows = var_rel_cba_INDEC > 10,
    #            direction = "column",
    #            palette = "viridis") %>% 
    # data_color(columns = var_rel_cbt_INDEC,
    #            rows = var_rel_cbt_INDEC > 10,
    #            direction = "column",
    #            palette = "viridis") %>% 
    tab_footnote(footnote = md("Fuente: Elaboración propia con base a los informes publicados por INDEC e ISEPCI"))
}

```


```{r echo=FALSE}
crear_tabla_canasta(2017)
```

\pagebreak

```{r echo=FALSE}
crear_tabla_canasta(2018)
```

\pagebreak

```{r echo=FALSE}
crear_tabla_canasta(2019)
```

\pagebreak


```{r echo=FALSE}
crear_tabla_canasta(2020)
```

\pagebreak

```{r echo=FALSE}
crear_tabla_canasta(2021)
```

\pagebreak

```{r echo=FALSE}
crear_tabla_canasta(2022)
```

\pagebreak

```{r echo=FALSE}
crear_tabla_canasta(2023)
```


\pagebreak

```{r echo=FALSE}
crear_tabla_canasta(2024)
```
